2022/09/27 11:55:51 [error] 36#36: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:55:52 [error] 37#37: *3 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:55:52 [error] 38#38: *5 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:55:52 [error] 39#39: *7 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:55:52 [error] 36#36: *9 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:55:58 [error] 36#36: *11 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6879"
2022/09/27 11:56:01 [error] 36#36: *9 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:56:15 [error] 36#36: *14 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:57:04 [error] 36#36: *14 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET /abc-def/egion-by-number?=number=89505555668 HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6878"
2022/09/27 11:57:56 [error] 37#37: *19 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Application.php:115
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET /abc-def/region-by-number HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6879"
2022/09/27 12:00:56 [error] 39#39: *22 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Request.php:299
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET /abc-def/region-by-number HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6879"
2022/09/27 12:00:56 [error] 39#39: *22 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Request.php:299
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET /abc-def/region-by-number HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6879"
2022/09/27 12:00:57 [error] 39#39: *22 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Request.php:299
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET /abc-def/region-by-number HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6879"
2022/09/27 12:00:57 [error] 39#39: *22 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "api/errors". in /app/vendor/yiisoft/yii2/base/Module.php:561
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction('api/errors')
#1 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii2/web/Request.php:299
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 {main}" while reading upstream, client: 192.168.10.1, server: , request: "GET /abc-def/region-by-number HTTP/1.1", upstream: "fastcgi://192.168.10.6:9000", host: "192.168.10.10:6879"
